# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopFK',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='adress',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.TextField(default='Empty'),
        ),
    ]
