# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20171002_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('commentLine', models.TextField(default='')),
                ('shopFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Shop')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='shopFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Shop'),
        ),
    ]
